api/urls.py
from django import views
from django.urls import path
from . import views


app_name = 'api'
urlpatterns = [
    path('', views.ProductsApiView.as_view(), name='products_list'),
    path('<slug:category_slug>/', views.product_list, name='products_list_by_category')
    
]

cart/urls.py
from django import views
from django.urls import path
from . import views

app_name = 'cart'

urlpatterns = [
    path('add/<int:product_pk>/', views.cart_add, name='cart_add'),
    path('remove/<int:product_pk>/', views.cart_remove, name='cart_remove'),
    path('detail/', views.cart_detail, name='cart_detail')
]

ecommerce/urls.py
from unicodedata import name
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('store.urls', namespace='store')),
    path('api/', include('api.urls', namespace='api')),
    path('account/', include('account.urls', namespace='account')),
    path('cart/', include('cart.urls', namespace='cart')),
    path('checkout/', include('checkout.urls', namespace='checkout'))
]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
    document_root=settings.MEDIA_ROOT)

store/urls.py
from django.urls import path
from . import views

app_name = 'store'
urlpatterns = [
    path('all-collections/<slug:category_slug>/', views.product_list_page, name='products_list_by_category'),
    path('all-collections/', views.product_list_page, name='products_list'),
    path('get-products', views.products_list, name='get_product_list'),
    path('get-products/<slug:category_slug>/', views.products_list, name='get_product_list'),    
    
    path('more_products/<slug:category_slug>/', views.more_products, name='more_products_by_category'),
    path('more_products/', views.more_products, name='more_products'),

    path('<int:pk>/<slug:product_slug>/', views.product_detail, name='product_detail')
]

store/models.py
from distutils.command.upload import upload
from email.policy import default
from tokenize import blank_re
from django.db import models
from django.conf import settings
from django.urls import reverse
from django.template.defaultfilters import slugify
# Create your models here.


class AvailableManager(models.Manager):
    def get_queryset(self):
        return super().get_queryset().filter(available=True)

class Product(models.Model):
    name = models.CharField(max_length=200)
    description = models.TextField()
    price = models.DecimalField(max_digits=10,
                                 decimal_places=3)
    create = models.DateTimeField(auto_now_add=True)
    update = models.DateTimeField(auto_now=True)
    slug = models.SlugField(max_length=200, db_index=True)
    available = models.BooleanField(default=True)

    stock = models.PositiveIntegerField(default=0)
    photo = models.ImageField(upload_to='products/%y/%m/%d', blank=True)
    
    objects = models.Manager()
    is_available = AvailableManager()

    class Meta:
        ordering = ('-price', '-stock')
        index_together = (('id','slug'),)

    def __str__(self):
        return self.name

    def save(self, *args, **kwags):
        self.slug = slugify(self.name)
        super(Product, self).save(*args, **kwags)
        
    def get_absolute_url(self):
        return reverse(
            'store:product_detail',
            args=[
                self.pk,
                self.slug
            ]
        )

class Image(models.Model):
    image = models.ImageField(upload_to='products/%y/%m/%d', blank=True)
    product = models.ForeignKey(Product,
                                on_delete=models.CASCADE,
                                related_name='images')
    create = models.DateTimeField(auto_now_add=True)
    class Meta:
        ordering = ['create']
    
class Category(models.Model):
    name = models.CharField(max_length=50)
    description = models.TextField()
    products = models.ManyToManyField(Product,
                                    related_name='categories',
                                    blank=True)
    slug = models.SlugField(max_length=200, unique=True)

    class Meta:
        ordering = ('name',)
        verbose_name = 'category'
        verbose_name_plural = 'categories'

    def save(self,*args, **kwargs):
        self.slug = slugify(self.name)
        super(Category, self).save(*args, **kwargs)

    def get_absolute_url(self):
        return reverse(
            'store:products_list_by_category',
            args=[self.slug]
        )

    def __str__(self):
        return self.name


# class PaymentInfo(models.Model):
#     PAYMENT_CHOICES = (
#         ('credit', 'Credit'),
#         ('cash', 'Cash')
#     )
#     STATUS = (
#         ('unconfirmed', 'Unconfirmed'),
#         ('confirmed', 'Confirmed'),
#         ('delivering', 'Delivering'),
#         ('delivered', 'Delivered')
#     )
#     order = models.OneToOneField(Order,
#                                 on_delete=models.CASCADE,
#                                 related_name='payment_info')
#     create = models.DateTimeField(auto_now_add=True)
#     update = models.DateTimeField(auto_now=True)
#     status = models.CharField(max_length=20, 
#                              choices=STATUS,
#                              default='unconfirmed')

store/views.py
from asyncio import constants
import json
import re
from time import process_time_ns, sleep
from django.contrib.auth.decorators import login_required
from django.shortcuts import get_object_or_404, render
from django.http import HttpResponse, JsonResponse
from django.views.generic import ListView
from django.core.paginator import Paginator, PageNotAnInteger, EmptyPage
from pkg_resources import require
from cart.cart import Cart

from cart.views import cart_add
from .models import *
from account.decorator import ajax_required
from django.views.decorators.http import require_http_methods
from cart.form import CartAddProductForm

from django.template.loader import render_to_string

from django.db.models import Q

# Create your views here.
PRODUCTS_PER_PAGE = 4

def product_list_page(request,category_slug = None):
    
    category_name = None
    if category_slug:
        category = get_object_or_404(Category, slug=category_slug)
        category_name = category.name

    context = {'category_slug':category_slug, 'category_name':category_name}
    return render(request, 'store/product_list_page.html', context)


@ajax_required
def products_list(request, category_slug=None):

    sleep(1)
        
    if request.method == 'GET':    
        q = request.GET.get('q')
    if q is None:
        q = ''
    
    if category_slug:
        category = get_object_or_404(Category, slug=category_slug)
        products = category.products.filter(
            Q(name__icontains=q) |
            Q(categories__name__icontains=q)
        ).distinct()
    else:
        products = Product.objects.filter(
            Q(name__icontains=q) |
            Q(categories__name__icontains=q)
        ).distinct()

    paginator = Paginator(products, PRODUCTS_PER_PAGE)
    page_obj = paginator.page(1)
    products = page_obj.object_list

    html = render_to_string('store/components/product_list.html', {'products' : products})

    page_info = json.dumps({
        'has_next': page_obj.has_next(),
        'has_previous': page_obj.has_previous(),
        'has_other_pages': page_obj.has_other_pages(),
        'current_page': page_obj.number,
        'q':q
    })
    
    script = render_to_string('store/components/handle_paginator.js', {'page_info': page_info, 'category_slug': category_slug})
    
    return JsonResponse({'html': html, 'script':script})

@ajax_required
def more_products(request, category_slug=None):
    sleep(1)
    
    if request.method == 'GET':    
        q = request.GET.get('q')
    if q is None:
        q = ''

    page = request.GET.get('page')
    print(page)

    if category_slug:
        category = get_object_or_404(Category, slug=category_slug)
        products = category.products.filter(
            Q(name__icontains=q) |
            Q(categories__name__icontains=q)
        ).distinct()
    else:
        products = Product.objects.filter(
            Q(name__icontains=q) |
            Q(categories__name__icontains=q)
        ).distinct()

    paginator = Paginator(products, PRODUCTS_PER_PAGE)
    try:
        page_obj = paginator.page(page)
    except (PageNotAnInteger, EmptyPage):
        page_obj = paginator.page(1)

    products = page_obj.object_list
    html = render_to_string('store/components/show_products.html', {'products': products})

    page_info = {
        'category_slug': category_slug,
        'has_next': page_obj.has_next(),
        'has_previous': page_obj.has_previous(),
        'has_other_pages': page_obj.has_other_pages(),
        'current_page': page_obj.number,
        'q':q
    }

    return JsonResponse({'html': html, 'page_info': page_info})

def product_detail(request, pk, product_slug=None):
    product = get_object_or_404(Product, pk=pk)
    cart = Cart(request)
    form = CartAddProductForm(stock=product.stock,cart_quantity=cart.quantity(product))
    return render(request, 'store/product_detail.html',{'product':product, 'form':form})

store/templates/store/main.html
{% extends 'main.html' %}
{% load static %}
{% load custom_tag %}
    {% block head %}
    <link rel="stylesheet" href="{% static 'store/styles/main.css' %}">
    <link rel="stylesheet" href="{% static 'store/styles/product_card.css' %}">
    <link rel="stylesheet" href="{% static 'cart/styles/cart.css' %}">
    <script src="{% static 'js/fetch.js' %}"></script>
    <script src="{% static 'js/validator.js' %}"></script>
    <script src="{% static 'js/toast.js' %}"></script>
    <script src="{% static 'cart/js/render_cart.js' %}"></script>
    {% block title %}{% endblock %}
    {% endblock %}
    
{% block content %}{% endblock %}    

{% block script %}
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>
    <script src="{% static 'store/js/main.js' %}"></script>
{% endblock %}

store/templates/store/product_detail.html
{% extends 'store/main.html' %}

{% block title %}Detail{% endblock %}

{% block content %}
<div style="grid-template-columns: 3fr 1fr; display: grid;">
    <div>
        <h2>{{product}}</h2>
        <p>Categories:</p>
        <ul>
            {% for category in product.categories.all %}
            <li><a href="{{category.get_absolute_url}}">{{category}}</a></li>
            {% endfor %}
        </ul>
        <ul>
            <li><h3>Price: {{product.price}}</h3></li>
        </ul>
        <p>{{product.description|linebreaks}}</p>

    </div>
    <div>
        <form id="cart-add-form"  method="POST">
            {% csrf_token %}
            {{form}}
            <input type="submit">
        </form>
    </div>    
</div>

<script>
    var form = document.getElementById('cart-add-form')

    var formData = new FormData()
    form.onsubmit = (e) => {
        e.preventDefault()
        formData.append('quantity', form.querySelector('select[name="quantity"]').value)
        formData.append('update', form.querySelector('input[name="update"]').value)
        fetchAPI({
            url:  "{% url 'cart:cart_add' product.pk %}",
            requestInit: {
                method: 'POST',
                body: formData,
                headers: {
                    'X-CSRFtoken': csrftoken,
                    'X-Requested-With': 'XMLHttpRequest'
                },
                origin: 'same-origin',
            },
            onSuccess: (data) => {
                if (data.status == 'ok'){
                    toast({
                        containerSelector: '#toast',
                        title: 'Added',
                        body: 'product was added to your cart',
                        type: 'success',
                        duration: 4000
                    })
                    renderCart(cart, "{% url 'cart:cart_detail' %}")
                }
                else {
                    toastErrors(data.errors)
                }
            },
            onError: (error) => {
                toast({
                    containerSelector: '#toast',
                    title: error.status || 'error',
                    body: error.statusText || error,
                    type: 'error',
                    duration: 4000
                })
            }
        })
    }
</script>
{% endblock %}

store/templates/store/product_list_page.html
{% extends 'store/main.html' %}
{% load custom_tag %}
{% block title %}Store{% endblock %}

{% block content %}
    <section class="section-products">
        <div id="container">
                <div class="row justify-content-center text-center">
                        <div class="col-md-8 col-lg-6">
                                <div class="header">
                                    {% if category_slug %}
                                        <h3>Featured Product</h3>
                                        <h2>{{category_name}}</h2>
                                    {% else %}
                                        <h3>Featured Product</h3>
                                        <h2>All collections</h2>
                                    {% endif %}
                                </div>
                        </div>
                </div>

                <div id="product-menu" >
                    <div id="product-options">
                        <!-- search bar -->
                        {% include 'store/components/search.html' %}
        
                        <hr class="boilline">
                        <!-- Products filter -->
                        {% include 'store/components/choices_filter.html' with choices=categories %}
                        <hr class="dashline">
                    </div>

                    <div id="products-container">
                    </div>                    
                </div>
        </div>
    </section>

    <script>
        var productsSection = document.querySelector('section[class="section-products"]')
        productsSection.classList.add('disabled')

        var productsContainer = document.getElementById('products-container')
        productsContainer.classList.add('disabled')
        "{% if category_slug %}"
        var url = "{% url 'store:get_product_list' category_slug=category_slug %}"
        "{% else %}"
        var url = "{% url 'store:get_product_list' %}"
        "{% endif %}"

        fetchAPI({
            url: url,
            requestInit: {
                method: 'GET',
                headers: {
                    'X-Requested-With': 'XMLHttpRequest'
                }
            },
            onSuccess: (data) => {
                if (data.html == ''){
                    toast({
                        containerSelector: '#toast',
                        title: 'Error',
                        body: 'Load products error, try request again',
                        type: 'error',
                        duration: 5000     
                    })
                }
                else {
                    productsContainer.insertAdjacentHTML("beforeend", data.html) 
                    var addBtns = [...document.getElementsByClassName('add-product-btn')]
                    updateAddBtn(addBtns)
                    var script = document.createElement('script')
                    script.innerHTML = data.script
                    document.body.appendChild(script)
                }
                productsSection.classList.remove('disabled')
                productsContainer.classList.remove('disabled')
            },
            onError: (error) => {
                toast({
                    containerSelector: '#toast',
                    title: error.status || 'error',
                    body: error.statusText || error,
                    type: 'error',
                    duration: 5000
                })
                productsSection.classList.remove('disabled')
                productsContainer.classList.remove('disabled')
            }
        })
    </script>


{% endblock %}

store/templates/store/show_products.html
{% load custom_tag %}

{% for product in products %}
    {% show_product product %}
{% endfor %}