api/urls.py
from django import views
from django.urls import path
from . import views


app_name = 'api'
urlpatterns = [
    path('', views.ProductsApiView.as_view(), name='products_list'),
    path('<slug:category_slug>/', views.product_list, name='products_list_by_category')
    
]

cart/urls.py
from django import views
from django.urls import path
from . import views

app_name = 'cart'

urlpatterns = [
    path('add/<int:product_pk>/', views.cart_add, name='cart_add'),
    path('remove/<int:product_pk>/', views.cart_remove, name='cart_remove'),
    path('detail/', views.cart_detail, name='cart_detail')
]

checkout/urls.py
from django.urls import path
from . import views
app_name = 'checkout'
urlpatterns = [
    path('', views.checkout, name='checkout'),
    path('order_detail', views.order_detail, name='order_detail')
]

ecommerce/urls.py
from unicodedata import name
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('store.urls', namespace='store')),
    path('api/', include('api.urls', namespace='api')),
    path('account/', include('account.urls', namespace='account')),
    path('cart/', include('cart.urls', namespace='cart')),
    path('checkout/', include('checkout.urls', namespace='checkout'))
]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
    document_root=settings.MEDIA_ROOT)

checkout/models.py
from multiprocessing.reduction import steal_handle
from django.db import models
from django.forms import SelectDateWidget
from pkg_resources import require
from store.models import Product
# Create your models here.
class Order(models.Model):

    STATUS_CHOICE = (
        ('UNCONFIRMED','Unconfirmed'),
        ('CONFIRMED', 'Confirmed'),
        ('DELIVERING', 'Delivering'),
        ('DELIVERED', 'Delivered')
    )

    first_name = models.CharField(max_length=50)
    last_name = models.CharField(max_length=50)
    phone = models.CharField(blank=True, null=True, max_length=15)
    email = models.EmailField()
    address = models.CharField(max_length=250)
    postal_code = models.CharField(max_length=20)
    city = models.CharField(max_length=100)
    create = models.DateTimeField(auto_now_add=True)
    update = models.DateTimeField(auto_now=True)
    paid = models.BooleanField(default=False)
    status = models.CharField(choices=STATUS_CHOICE, default=STATUS_CHOICE[0][1], max_length=50)

class OrderItem(models.Model):
    order = models.ForeignKey(Order, on_delete=models.CASCADE, related_name='items')
    product = models.ForeignKey(Product, on_delete=models.CASCADE, related_name='order_items')
    price = models.DecimalField(max_digits=10, decimal_places=3)
    quantity = models.PositiveSmallIntegerField(default=1)

    def __str__(self):
        return str(self.id)
    
    def get_cost(self):
        return self.price * self.quantity

cart/views.py
from time import sleep
from django import forms
from django.http import JsonResponse
from django.views.decorators.http import require_http_methods
from django.shortcuts import get_object_or_404, render
from store.models import Product
from .form import CartAddProductForm
from .cart import Cart
# Create your views here.

from account.decorator import ajax_required

@ajax_required
@require_http_methods(['POST'])
def cart_add(request, product_pk):
    sleep(0.5)
    cart = Cart(request)
    product = get_object_or_404(Product, pk=product_pk)
    form = CartAddProductForm(
        request.POST,
        stock=product.stock,
        cart_quantity=cart.quantity(product)
    )
    if form.is_valid():
        cart.add(
            product=product,
            quantity=form.cleaned_data['quantity'],
            update_quantity=form.cleaned_data['update']
        )
        return JsonResponse({'status':'ok'})
    return JsonResponse({'status':'error', 'errors': form.errors})

@ajax_required
def cart_remove(request, product_pk):
    sleep(0.5)
    product = get_object_or_404(Product, pk=product_pk)
    cart = Cart(request)
    cart.remove(product)
    return JsonResponse({'status':'ok'})

@ajax_required
def cart_detail(request):
    cart = Cart(request)
    return render(request, 'cart/cart.html',{'cart': cart})

checkout/views.py
from http.client import OK
from django.http import HttpResponse, JsonResponse
from django.shortcuts import redirect, render
from account.decorator import ajax_required
from django.views.decorators.http import require_http_methods
from cart.cart import Cart
from .form import CreateOrderForm
# Create your views here.

def checkout(request):
    cart = Cart(request)
    context = {'cart': cart}
    if request.method == 'POST':
        return redirect('checkout:order_detail')
    else:
        return render(request, 'checkout/checkout_page.html', context)

def order_detail(request):
    form = CreateOrderForm()
    return render(request,'checkout/create_order_form.html',{'form': form})

checkout/templates/checkout/cart.html
{% for item in cart %}
{% include 'checkout/cart_item.html' %}
{% endfor %}

checkout/templates/checkout/cart_detail.html
                <div class="col-lg-8">
                  <div class="p-5">
                    <div class="d-flex justify-content-between align-items-center mb-5">
                      <h1 class="fw-bold mb-0 text-black" style="color: #de6363;">Shopping Cart</h1>
                      <h6 class="mb-0 text-muted">3 items</h6>
                    </div>
                    <hr class="my-4">
                    <div id="item-container">
                        {% include 'checkout/cart.html'%}                 
                    </div>

                    <div class="pt-5">
                      <h6 class="mb-0"><a href="#!" class="text-body"><i
                            class="fas fa-long-arrow-alt-left me-2"></i>Back to shop</a></h6>
                    </div>
                  </div>
                </div>


                

checkout/templates/checkout/cart_item.html
{% load static %}
<div class="row mb-4 d-flex justify-content-between align-items-center cart-item">
    <div class="col-md-2 col-lg-2 col-xl-2">
        {% with product=item.product %}
      <img
        src="{% if product.photo %}{{item.product.photo.url}}{% else %}{% static 'store/images/no-image.jpg' %}{% endif %}"
        class="img-fluid rounded-3" alt="Cotton T-shirt">
        {% endwith %}
    </div>
    <div class="col-md-3 col-lg-3 col-xl-3">
      <h6 class="text-muted"></h6>
      <h5 style="font-weight: 800;" class="text-black mb-0"><a style="text-decoration: none; color: rgb(59, 59, 59)"  href="{{item.product.get_absolute_url }}">{{item.product|truncatechars:35}}</a></h5>
    </div>
    <form class="col-md-3 col-lg-3 col-xl-2 d-flex">    
      <a data-action="remove" href="{% url 'cart:cart_add' item.product.pk %}" class="btn btn-link px-2 cart-btn">
        <i class="fas fa-minus"></i>
      </a>

      <input id="form1" name="quantity" value="{{item.quantity}}" type="number"
        class="form-control form-control-sm" />

      <a data-action="add" href="{% url 'cart:cart_add' item.product.pk %}" class="btn btn-link px-2 cart-btn">
        <i class="fas fa-plus"></i>
      </a>
    </form>
    <div class="col-md-3 col-lg-2 col-xl-2 offset-lg-1">
      <h6 data-price="{{item.product.price}}" class="mb-0 price">$ {{item.total_price}}</h6>
    </div>
    <div class="col-md-1 col-lg-1 col-xl-1 text-end">
      <a href="{% url 'cart:cart_remove' item.product.pk %}" class="remove-btn" style="color: #cecece;"><i class="fas fa-trash-alt"></i></a>
    </div>
    <hr class="my-4 dashline">
  </div>

checkout/templates/checkout/checkout_detail.html
                <div class="col-lg-4 bg-grey">
                  <div class="p-5">
                    <h3 class="fw-bold mb-5 mt-2 pt-1" style="color: #de6363;">Summary</h3>
                    <hr class="my-4">
  
                    <div class="d-flex justify-content-between mb-4">
                      <h5 class="text-uppercase">items 3</h5>
                      <h5>€ 132.00</h5>
                    </div>
  
                    <h5 class="text-uppercase mb-3">Shipping</h5>
  
                    <div class="mb-4 pb-2">
                      <select class="select">
                        <option value="1">Standard-Delivery- €5.00</option>
                        <option value="2">Two</option>
                        <option value="3">Three</option>
                        <option value="4">Four</option>
                      </select>
                    </div>
  
                    <h5 class="text-uppercase mb-3">Give code</h5>
                    <form id="checkout-form" method="POST" >
                      {% csrf_token %}
                      <div class="mb-5">
                        <div class="form-outline">
                          <div class="form__group">
                            <input type="text" id="id_coupon_code" class="form-control form-control-lg" />
                            <label class="form-label" for="form3Examplea2">Enter your code</label>
                            <span class="form__message"></span>
                          </div>
                        </div>
                      </div>
    
                      <hr class="my-4">
                      
                      <div class="d-flex justify-content-between mb-5">
                        <h5 class="text-uppercase">Total price</h5>
                        <h5>€ 137.00</h5>
                      </div>
    
                      <button  type="submit" class="btn btn-block btn-lg form__button"
                      style="width: 100%; color: white; background-color: #de6363;">Checkout</button>
                    </form>
                  </div>
                </div>

<script>
  validator({
    formSelector:'#checkout-form',
    errorSelector:'.form__message',
    errorClass: 'invalid',
    ruleOptions: [
    ]
  })
</script>

checkout/templates/checkout/checkout_page.html
{% extends 'checkout/main.html' %}

{% block title %}Checkout{% endblock %}

{% block content %}

<section class="h-100 h-custom">
    <div class="row d-flex justify-content-center align-items-center h-100">
      <div class="col-0">
        <div class="card card-registration card-registration-2" style="border: none;">
          <div class="card-body p-0">
            <div class="row g-0">
                {% include 'checkout/cart_detail.html' %}
                {% include 'checkout/checkout_detail.html' %}
            </div>
          </div>
        </div>
      </div>
    </div>
</section>

{% endblock %}

checkout/templates/checkout/create_order_form.html
{% extends 'checkout/main.html' %}
{% load static %}

{% block title %}Order detail{% endblock %}
{% block content %}
<div id="order-container">
        <form method="POST" id="order-form" class="form">
            {% csrf_token %}
            <h1 class="form__title">Shipping detail</h1>
                {% for field in form %}
                <div class="form__group">
                    <label for="{{field.id_for_label}}">{{field.label}}</label>
                    <input id="{{field.id_for_label}}" placeholder="{{field.label}}" type="{{field.field.widget.input_type}}" name="{{field.name}}">
                    <span class="form__message"></span>
                    <span class="form__error"></span>
                </div>
                {% endfor %}
                <hr class="dashline">
                <button type="submit" class="form__button" id="form__login">Place order</button>
        </form>
        <div class="cart-summarize-container">
            <div id="cart-summarize">
                <h3 class="cart__title">ORDER</h3>
                
                <ul class="list__group">
                    <hr class="boldline">
                    {% for item in cart %}
                    <li class="group__item">
                        <span class="item important">{{item.product|truncatechars:30}}</span>
                        <span class="item__detail">$ {{item.product.price}}</span>
                    </li>
                    <li class="group__item">
                        <span class="item">Quantity</span>
                        <span class="item__detail">x {{item.quantity}}</span>
                    </li>
                    
                    <hr class="pseudoline">
                    {% endfor %}

                    <hr class="dashline">
                    <hr class="pseudoline">

                    <li class="group__item">
                        <span class="item">Cart total</span>
                        <span class="item__detail important">$ {{cart.total_price}}</span>
                    </li>
        
                    <li class="group__item">
                        <span class="item">Discount</span>
                        <span class="item__detail">43.000 VND</span>
                    </li>
        
                    <li class="group__item">
                        <span class="item important">Shipping cost</span>
                        <span class="item__detail important">0 VND</span>
                    </li>
                    <hr class="pseudoline">
                    <hr class="dashline">
                    <hr class="pseudoline">
                    <hr class="pseudoline">

                    
                    <li class="group__item">
                        <span class="item important" style="font-size: 25px;">Total cost</span>
                        <span class="item__detail totalcost" style="font-size: 25px;">$ {{cart.total_price}}</span>
                    </li>
        
                </ul>

            </div>    
        </div>
        
    
</div>

<script>
    validator({
                formSelector:'#order-form',
                errorSelector:'.form__message',
                errorClass: 'invalid',
                ruleOptions: [
                    validator.isRequired('#id_first_name', 'This field is required'),
                    validator.isRequired('#id_last_name', 'This field is required'),
                    validator.minLength('#id_phone', 8, 'At least 8 character length'),
                    validator.isRequired('#id_phone', 'This field is requuired'),
                ],
    })
</script>

<script src="{% static 'checkout/js/responsive.js' %}"></script>

{% endblock %}

checkout/templates/checkout/main.html
{% extends 'main.html' %}
{% load static %}
{% load custom_tag %}
    {% block head %}
    <link rel="stylesheet" href="{% static 'checkout/styles/main.css' %}">
    <script src="{% static 'js/fetch.js' %}"></script>
    <script src="{% static 'js/validator.js' %}"></script>
    <script src="{% static 'js/toast.js' %}"></script>
    <script src="{% static 'cart/js/render_cart.js' %}"></script>
    {% block title %}{% endblock %}
    {% endblock %}
</head>

{% block content %}{% endblock %}    

{% block script %}
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>
    <script src="{% static 'checkout/js/main.js' %}"></script>
{% endblock %}