account/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views
from django.urls import reverse_lazy
from . import views


app_name = 'account'
urlpatterns = [
    path('login/', views.login_page, name='login') ,
    path('login_user/',views.login_user, name='login_user'),
    path('logout/', auth_views.LogoutView.as_view(next_page=reverse_lazy('account:login')), name='logout'),
    path('password-change/', views.password_change_form,name='password_change'),
    path('password-change/request', views.password_change_request, name='password_change_request'),
    path('password-reset/', views.password_reset_form, name='password_reset'),
    path('password-reset/request', views.password_reset_request, name='password_reset_request'),
    path('password-reset/confirm/<uidb64>/<token>', views.password_reset_confirm_form, name='password_reset_confirm'),
    path('password-reset/confirm/request/<uidb64>/<token>', views.password_reset_confirm_request, name='password_reset_confirm_request'),
    path('register/', views.register_page, name='register'),
    path('register/request', views.register_request, name='register_request'),
    path('activate/<uidb64>/<token>', views.account_activation, name='account_activation'),
    path('activate/', views.account_activation_request, name='account_activation_request'),
    path('add-info/', views.add_info, name='add_info')
]

api/urls.py
from django import views
from django.urls import path
from . import views


app_name = 'api'
urlpatterns = [
    path('', views.ProductsApiView.as_view(), name='products_list'),
    path('<slug:category_slug>/', views.product_list, name='products_list_by_category')
    
]

cart/urls.py
from django import views
from django.urls import path
from . import views

app_name = 'cart'

urlpatterns = [
    path('add/<int:product_pk>/', views.cart_add, name='cart_add'),
    path('remove/<int:product_pk>/', views.cart_remove, name='cart_remove'),
    path('detail/', views.cart_detail, name='cart_detail')
]

checkout/urls.py
from django.urls import path
from . import views
app_name = 'checkout'
urlpatterns = [
    path('', views.checkout, name='checkout'),
    path('order_detail', views.order_detail, name='order_detail')
]

ecommerce/urls.py
from unicodedata import name
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('store.urls', namespace='store')),
    path('api/', include('api.urls', namespace='api')),
    path('account/', include('account.urls', namespace='account')),
    path('cart/', include('cart.urls', namespace='cart')),
    path('checkout/', include('checkout.urls', namespace='checkout'))
]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
    document_root=settings.MEDIA_ROOT)

templates/main.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block title %}{% endblock %} </title>
    <link rel="stylesheet" href="{% static 'styles/main.css' %}">
    <link rel="stylesheet" href="{% static 'styles/toast.css' %}">
`    <link rel="stylesheet" href="{% static 'styles/fontawesome-free-6.1.1-web/css/all.min.css' %}">
    <link rel="stylesheet" href="{% static 'cart/styles/cart.css' %}">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
    <script>
        function getCookie(name) {
            let cookieValue = null;
            if (document.cookie && document.cookie !== '') {
                const cookies = document.cookie.split(';');
                for (let i = 0; i < cookies.length; i++) {
                    const cookie = cookies[i].trim();
                    // Does this cookie string begin with the name we want?
                    if (cookie.substring(0, name.length + 1) === (name + '=')) {
                        cookieValue = decodeURIComponent(cookie.substring(name.length + 1));
                        break;
                    }
                }
            }
            return cookieValue;
        }
        const csrftoken = getCookie('csrftoken');
    </script>

    {% block head %} {% endblock %}
</head>
<body>

    <div id="toast"></div>

    {% include 'nav.html' %}    

    <div id="content">
        {% block content %} {% endblock %}
    </div>

    {% block script %}{% endblock %}
</body>
</html>

templates/nav.html
{% load static %}
{% load custom_tag %}

<div id="header" style="position: fixed; width: 100%; top: 0; z-index:99999999999;">
    <nav class="navbar navbar-expand-lg navbar-light bg-light">
        <div class="container-fluid ">
          <!-- add home page link -->
          <a class="navbar-brand" href="#">Ecommerce</a>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse " id="navbarSupportedContent">

            <form class="d-flex" action="" method="GET">
              <input name="search" class="form-control me-2" type="search" placeholder="Search" aria-label="Search">
              <button class="btn btn-outline-success" type="submit">Search</button>
            </form>

            <ul class="navbar-nav ms-auto mb-2 mb-lg-0">
              <li class="nav-item">
                          <!-- add home page link -->
                <a class="nav-link active" aria-current="page" href="#">Home</a>
              </li>
              <li class="nav-item dropdown">
                <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                  Categories
                </a>
                {% categories_dropdown %}
              </li>

              <li class="nav-item dropdown">
                <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                  Account
                </a>
                <!--  -->
                  <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
                    {% if request.user.is_authenticated %}
                      <li class="dropdown-item">Welcome {{request.user.get_name}}</li>
                      <hr class="dropdown-divider">
                      <li><a class="dropdown-item" href="#">Profile</a></li>
                      <li><a class="dropdown-item" href="{% url 'account:logout' %}">Logout</a></li>
                      <li><a class="dropdown-item" href="{% url 'account:register' %}">Register</a></li>

                    {% else %}
                    <li><a class="dropdown-item" href="{% url 'account:logout' %}">Login</a></li>
                    <li><a class="dropdown-item" href="{% url 'account:register' %}">Register</a></li>
                    {% endif %}
                  </ul>
              </li>
              <li id="cart-btn" class="nav-item dropdown"><a class="nav-link dropdown-toggle" role="button" href="#">Cart</a></li>
            </ul>
          </div>
        </div>
      </nav>
</div>

<div id="cart-overlay"></div>
  <section id="cart-container">
    <div class="row" id="cart">

    </div>
    <a href="{% url 'checkout:checkout' %}" class="btn btn-outline-dark btn-squared" style="margin:10px 0px; width:150%;">Checkout</a>
  </section>

<script>
  var cartBtn = document.getElementById('cart-btn')
  var cart_container = document.getElementById('cart-container')
  var cart_overlay = document.getElementById('cart-overlay')

  cartBtn.onclick = (e) => {
    e.preventDefault()
    cart_container.classList.toggle('active')
    cart_overlay.classList.toggle('active')
  }
  
  var cart = document.getElementById('cart')
  renderCart(cart,"{% url 'cart:cart_detail' %}")
</script>